<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[Validating: Ground Flooring]]>
    </line>
    <line>
      <![CDATA[Expected - Quantity: 2404.57, Unit: sqft, Total Cost: 2,36,550.44]]>
    </line>
    <line>
      <![CDATA[Actual - Quantity: Not Found, Unit: Not Found, Total Cost: Not Found]]>
    </line>
    <line>
      <![CDATA[Test FAILED for: Ground Flooring]]>
    </line>
  </reporter-output>
  <suite started-at="2025-02-26T23:09:08 IST" name="Default suite" finished-at="2025-02-26T23:11:46 IST" duration-ms="157123">
    <groups>
    </groups>
    <test started-at="2025-02-26T23:09:08 IST" name="Default test" finished-at="2025-02-26T23:11:46 IST" duration-ms="157123">
      <class name="tests.ValidateQuotationTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:tests.ValidateQuotationTest@408d971b]" started-at="2025-02-26T23:09:08 IST" name="setup" finished-at="2025-02-26T23:09:17 IST" duration-ms="8071" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="validateQuotationDetails()[pri:0, instance:tests.ValidateQuotationTest@408d971b]" started-at="2025-02-26T23:09:17 IST" name="validateQuotationDetails" finished-at="2025-02-26T23:11:45 IST" duration-ms="148699" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at tests.ValidateQuotationTest.validateQuotationDetails(ValidateQuotationTest.java:27)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Validating: Ground Flooring]]>
            </line>
            <line>
              <![CDATA[Expected - Quantity: 2404.57, Unit: sqft, Total Cost: 2,36,550.44]]>
            </line>
            <line>
              <![CDATA[Actual - Quantity: Not Found, Unit: Not Found, Total Cost: Not Found]]>
            </line>
            <line>
              <![CDATA[Test FAILED for: Ground Flooring]]>
            </line>
          </reporter-output>
        </test-method> <!-- validateQuotationDetails -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:tests.ValidateQuotationTest@408d971b]" started-at="2025-02-26T23:11:45 IST" name="tearDown" finished-at="2025-02-26T23:11:46 IST" duration-ms="300" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- tests.ValidateQuotationTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
